use_frameworks!

platform :ios, '8.0'

target 'GFLoadingAnimationView_Example' do
  pod 'GFLoadingAnimationView', :path => '../'

  target 'GFLoadingAnimationView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
