use_frameworks!

platform :ios, '9.0'

target 'GFLoadingAnimationView_Example' do
  pod 'GFLoadingAnimationView', :path => '../'
  pod 'iOS-Color-Picker'

  target 'GFLoadingAnimationView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
